/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-18 at 22:56:50 UTC 
 * Modify at your own risk.
 */

package com.appspot.tombn_songm_haystack.haystack.model;

/**
 * Model definition for DbEvent.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the haystack. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DbEvent extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String address;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String category;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("comment_size") @com.google.api.client.json.JsonString
  private java.lang.Long commentSize;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> comments;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String entityKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("from_date_time")
  private java.lang.String fromDateTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("last_touch_date_time")
  private java.lang.String lastTouchDateTime;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double lat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> likes;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("likes_size") @com.google.api.client.json.JsonString
  private java.lang.Long likesSize;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double lon;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("to_date_time")
  private java.lang.String toDateTime;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAddress() {
    return address;
  }

  /**
   * @param address address or {@code null} for none
   */
  public DbEvent setAddress(java.lang.String address) {
    this.address = address;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCategory() {
    return category;
  }

  /**
   * @param category category or {@code null} for none
   */
  public DbEvent setCategory(java.lang.String category) {
    this.category = category;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCommentSize() {
    return commentSize;
  }

  /**
   * @param commentSize commentSize or {@code null} for none
   */
  public DbEvent setCommentSize(java.lang.Long commentSize) {
    this.commentSize = commentSize;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getComments() {
    return comments;
  }

  /**
   * @param comments comments or {@code null} for none
   */
  public DbEvent setComments(java.util.List<java.lang.String> comments) {
    this.comments = comments;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public DbEvent setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEntityKey() {
    return entityKey;
  }

  /**
   * @param entityKey entityKey or {@code null} for none
   */
  public DbEvent setEntityKey(java.lang.String entityKey) {
    this.entityKey = entityKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFromDateTime() {
    return fromDateTime;
  }

  /**
   * @param fromDateTime fromDateTime or {@code null} for none
   */
  public DbEvent setFromDateTime(java.lang.String fromDateTime) {
    this.fromDateTime = fromDateTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLastTouchDateTime() {
    return lastTouchDateTime;
  }

  /**
   * @param lastTouchDateTime lastTouchDateTime or {@code null} for none
   */
  public DbEvent setLastTouchDateTime(java.lang.String lastTouchDateTime) {
    this.lastTouchDateTime = lastTouchDateTime;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLat() {
    return lat;
  }

  /**
   * @param lat lat or {@code null} for none
   */
  public DbEvent setLat(java.lang.Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getLikes() {
    return likes;
  }

  /**
   * @param likes likes or {@code null} for none
   */
  public DbEvent setLikes(java.util.List<java.lang.String> likes) {
    this.likes = likes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getLikesSize() {
    return likesSize;
  }

  /**
   * @param likesSize likesSize or {@code null} for none
   */
  public DbEvent setLikesSize(java.lang.Long likesSize) {
    this.likesSize = likesSize;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLon() {
    return lon;
  }

  /**
   * @param lon lon or {@code null} for none
   */
  public DbEvent setLon(java.lang.Double lon) {
    this.lon = lon;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public DbEvent setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getToDateTime() {
    return toDateTime;
  }

  /**
   * @param toDateTime toDateTime or {@code null} for none
   */
  public DbEvent setToDateTime(java.lang.String toDateTime) {
    this.toDateTime = toDateTime;
    return this;
  }

  @Override
  public DbEvent set(String fieldName, Object value) {
    return (DbEvent) super.set(fieldName, value);
  }

  @Override
  public DbEvent clone() {
    return (DbEvent) super.clone();
  }

}
